set(LLVM_LINK_COMPONENTS
  Core
  Support
  TestingSupport
  )

add_feme_unittest(FeMeGraphicsTests
  DomainInvocationsTest.cpp
  ExecutorTest.cpp
  GeometryInputsTest.cpp
  GeometryStreamCollectionTest.cpp
  GeometryStreamTest.cpp
  GeometryTest.cpp
  ImageFixtureTest.cpp
  LayeredRenderingTest.cpp
  PatchPipelineTest.cpp
  PatchTest.cpp
  PipelineTest.cpp
  PreparedDrawTest.cpp
  SceneTest.cpp
  StageLinkTest.cpp
  TessellationTest.cpp
  TessellatorTest.cpp
  )
target_link_libraries(FeMeGraphicsTests
  PRIVATE
  FeMeGraphics
  FeMeTransformsDXIL
  )
