set(LLVM_LINK_COMPONENTS
  Core
  Support
  TargetParser
  TestingSupport
  )

add_feme_unittest(FeMeConversionSPIRVToLLVMTests
  SPIRVToLLVMTest.cpp
  )
target_link_libraries(FeMeConversionSPIRVToLLVMTests
  PRIVATE
  FeMeConversionSPIRVToLLVM
  MLIRIR
  MLIRLLVMDialect
  MLIRParser
  MLIRPass
  MLIRSPIRVDialect
  )
