//===- SPIRVImporter.cpp - SPIR-V binary importer ------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM
// Exceptions. See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "feme/Import/SPIRV/SPIRVImporter.h"

#include "feme/Core/Context.h"
#include "feme/Core/Module.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/Target/SPIRV/Deserialization.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Error.h"

using namespace feme;

namespace {

// SPIR-V opcode numbers this file needs (see the SPIR-V specification's
// "Instructions" chapter); not worth pulling in a whole opcode-enum header
// for two constants.
constexpr uint32_t kOpExtInstImport = 11;
constexpr uint32_t kOpExtInst = 12;
constexpr uint32_t kSPIRVHeaderWords = 5;

/// Decodes a null-terminated SPIR-V "Literal String" starting at
/// `Words[Index]` (a stream of 32-bit words, each holding up to 4 UTF-8
/// bytes in little-endian order, terminated by the first zero byte -- see
/// the SPIR-V specification's "Literal String" encoding), advancing
/// `Index` past the terminator.
std::string decodeLiteralString(llvm::ArrayRef<uint32_t> Words,
                                unsigned &Index) {
  std::string Result;
  for (; Index < Words.size(); ++Index) {
    uint32_t Word = Words[Index];
    for (unsigned Shift = 0; Shift < 32; Shift += 8) {
      char C = static_cast<char>((Word >> Shift) & 0xff);
      if (C == '\0') {
        ++Index;
        return Result;
      }
      Result.push_back(C);
    }
  }
  return Result;
}

/// `VK_KHR_shader_non_semantic_info` (roadmap E19): the SPIR-V
/// specification defines every instruction in a `NonSemantic.*` extended
/// instruction set to have no effect on a module's semantics, and
/// explicitly permits a consumer that does not implement a given set to
/// ignore every `OpExtInst` referencing it. MLIR's own SPIR-V deserializer
/// has no generic "ignore" case for this, though --
/// `dispatchToExtensionSetAutogenDeserialization` fails outright for any
/// extended-instruction-set name it does not recognize by autogenerated
/// dispatch table, `NonSemantic.*` included -- so this ICD honors that
/// "ignorable" contract itself, at the one layer that can: strip the
/// `OpExtInstImport` that names such a set, and every `OpExtInst` that
/// references it, out of the binary word stream before MLIR ever sees it.
/// Any other extended-instruction-set import (e.g. `GLSL.std.450`, which
/// MLIR's dispatch table does recognize) is left untouched. Returns a copy
/// of \p Words with those instructions removed, or \p Words itself
/// (unmodified) if no `NonSemantic.*` import is present -- the common case,
/// so this is a no-op for every module that doesn't use the extension.
llvm::SmallVector<uint32_t>
stripNonSemanticExtInst(llvm::ArrayRef<uint32_t> Words) {
  if (Words.size() <= kSPIRVHeaderWords)
    return llvm::SmallVector<uint32_t>(Words);

  // First pass: find every `OpExtInstImport` result <id> naming a
  // `NonSemantic.*` set. A malformed instruction stream (bad word count,
  // truncated) is left for the real deserializer to reject -- this pass
  // only ever narrows what gets stripped, never invents new errors.
  llvm::DenseSet<uint32_t> NonSemanticSetIds;
  for (size_t I = kSPIRVHeaderWords; I < Words.size();) {
    uint32_t WordCount = Words[I] >> 16;
    uint32_t Opcode = Words[I] & 0xffff;
    if (WordCount == 0 || I + WordCount > Words.size())
      break;
    if (Opcode == kOpExtInstImport && WordCount >= 3) {
      unsigned NameIndex = static_cast<unsigned>(I + 2);
      std::string Name = decodeLiteralString(Words, NameIndex);
      if (llvm::StringRef(Name).starts_with("NonSemantic."))
        NonSemanticSetIds.insert(Words[I + 1]);
    }
    I += WordCount;
  }

  if (NonSemanticSetIds.empty())
    return llvm::SmallVector<uint32_t>(Words);

  // Second pass: copy every instruction except the `NonSemantic.*`
  // `OpExtInstImport`s found above and every `OpExtInst` referencing one of
  // them (its `Set` operand, the third operand -- word index `I + 3`).
  llvm::SmallVector<uint32_t> Result(Words.begin(),
                                     Words.begin() + kSPIRVHeaderWords);
  for (size_t I = kSPIRVHeaderWords; I < Words.size();) {
    uint32_t WordCount = Words[I] >> 16;
    uint32_t Opcode = Words[I] & 0xffff;
    if (WordCount == 0 || I + WordCount > Words.size()) {
      // Malformed tail: copy the rest verbatim and let the real
      // deserializer produce the error.
      Result.append(Words.begin() + I, Words.end());
      break;
    }
    bool IsNonSemanticImport = Opcode == kOpExtInstImport && WordCount >= 3 &&
                               NonSemanticSetIds.count(Words[I + 1]);
    bool IsNonSemanticExtInst = Opcode == kOpExtInst && WordCount >= 4 &&
                                NonSemanticSetIds.count(Words[I + 3]);
    if (!IsNonSemanticImport && !IsNonSemanticExtInst)
      Result.append(Words.begin() + I, Words.begin() + I + WordCount);
    I += WordCount;
  }
  return Result;
}

} // namespace

llvm::Expected<Module> SPIRVImporter::import(llvm::MemoryBufferRef Buffer,
                                             const ImportOptions &Opts,
                                             Context &Ctx) const {
  // SPIR-V binaries are a stream of 32-bit words (see the SPIR-V
  // specification); reject inputs that cannot possibly be one rather than
  // reading past the end of the buffer.
  if (Buffer.getBufferSize() % sizeof(uint32_t) != 0)
    return llvm::createStringError(
        llvm::inconvertibleErrorCode(),
        "SPIR-V binary module must contain an integral number of 32-bit "
        "words");

  mlir::MLIRContext &MLIRCtx = Ctx.getMLIRContext();
  MLIRCtx.loadDialect<mlir::spirv::SPIRVDialect>();

  auto RawBinary = llvm::ArrayRef(
      reinterpret_cast<const uint32_t *>(Buffer.getBufferStart()),
      Buffer.getBufferSize() / sizeof(uint32_t));
  llvm::SmallVector<uint32_t> Filtered = stripNonSemanticExtInst(RawBinary);
  llvm::ArrayRef<uint32_t> Binary = Filtered;

  mlir::spirv::DeserializationOptions DeserOpts;
  DeserOpts.enableControlFlowStructurization =
      Opts.SPIRVEnableControlFlowStructurization;

  bool MayRetry = DeserOpts.enableControlFlowStructurization &&
                  Opts.SPIRVFallBackToUnstructuredControlFlow;

  mlir::OwningOpRef<mlir::spirv::ModuleOp> SpirvModule;
  {
    // Only the *final* attempt's diagnostics should reach the caller: a
    // structurization failure that the retry below recovers from is not an
    // error the user needs to hear about.
    mlir::ScopedDiagnosticHandler Swallow(
        &MLIRCtx, [MayRetry](mlir::Diagnostic &) {
          return MayRetry ? mlir::success() : mlir::failure();
        });
    SpirvModule = mlir::spirv::deserialize(Binary, &MLIRCtx, DeserOpts);
  }

  if (!SpirvModule && MayRetry) {
    DeserOpts.enableControlFlowStructurization = false;
    SpirvModule = mlir::spirv::deserialize(Binary, &MLIRCtx, DeserOpts);
  }

  if (!SpirvModule)
    return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                   "failed to deserialize SPIR-V module");

  return Module::fromMLIR(std::move(SpirvModule));
}

llvm::StringRef SPIRVImporter::getFormatName() const { return "spirv"; }
