//===- SPIRVImporter.cpp - SPIR-V binary importer ------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM
// Exceptions. See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "feme/Import/SPIRV/SPIRVImporter.h"

#include "feme/Core/Context.h"
#include "feme/Core/Module.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVOps.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/Target/SPIRV/Deserialization.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Error.h"

#include <utility>

using namespace feme;

namespace {

// SPIR-V opcode numbers this file needs (see the SPIR-V specification's
// "Instructions" chapter); not worth pulling in a whole opcode-enum header
// for two constants.
constexpr uint32_t kOpExtInstImport = 11;
constexpr uint32_t kOpExtInst = 12;
constexpr uint32_t kOpTypeFloat = 22;
constexpr uint32_t kOpTypeVector = 23;
constexpr uint32_t kOpTypeStruct = 30;
constexpr uint32_t kOpTypeFunction = 33;
constexpr uint32_t kOpFunction = 54;
constexpr uint32_t kOpFunctionParameter = 55;
constexpr uint32_t kOpFunctionEnd = 56;
constexpr uint32_t kOpFunctionCall = 57;
constexpr uint32_t kOpCompositeConstruct = 80;
constexpr uint32_t kOpCompositeExtract = 81;
constexpr uint32_t kOpImageSampleExplicitLod = 88;
constexpr uint32_t kOpImageSampleDrefExplicitLod = 90;
constexpr uint32_t kOpImageSampleProjExplicitLod = 92;
constexpr uint32_t kOpImageSampleProjDrefExplicitLod = 94;
constexpr uint32_t kOpImage = 100;
constexpr uint32_t kOpImageQuerySizeLod = 103;
constexpr uint32_t kOpImageQueryLevels = 106;
constexpr uint32_t kOpImageQuerySamples = 107;
constexpr uint32_t kOpFDiv = 136;
constexpr uint32_t kOpCapability = 17;
constexpr uint32_t kOpName = 5;
constexpr uint32_t kOpDecorate = 71;
constexpr uint32_t kCapabilityLinkage = 5;
constexpr uint32_t kDecorationLinkageAttributes = 41;
constexpr uint32_t kLinkageTypeImport = 1;
constexpr uint32_t kSPIRVHeaderWords = 5;

/// Decodes a null-terminated SPIR-V "Literal String" starting at
/// `Words[Index]` (a stream of 32-bit words, each holding up to 4 UTF-8
/// bytes in little-endian order, terminated by the first zero byte -- see
/// the SPIR-V specification's "Literal String" encoding), advancing
/// `Index` past the terminator.
std::string decodeLiteralString(llvm::ArrayRef<uint32_t> Words,
                                unsigned &Index) {
  std::string Result;
  for (; Index < Words.size(); ++Index) {
    uint32_t Word = Words[Index];
    for (unsigned Shift = 0; Shift < 32; Shift += 8) {
      char C = static_cast<char>((Word >> Shift) & 0xff);
      if (C == '\0') {
        ++Index;
        return Result;
      }
      Result.push_back(C);
    }
  }
  return Result;
}

/// Appends \p Str to \p Words, encoded per the SPIR-V specification's own
/// "Literal String" rule -- a NUL-terminated UTF-8 byte sequence packed
/// four bytes per word, little-endian within each word, then padded with
/// zero bytes out to a whole word -- mirroring `decodeLiteralString`'s own
/// byte order exactly. Returns the number of words appended.
unsigned appendLiteralString(llvm::SmallVectorImpl<uint32_t> &Words,
                             llvm::StringRef Str) {
  size_t Start = Words.size();
  unsigned WordCount = static_cast<unsigned>(Str.size() / 4) + 1;
  Words.resize(Words.size() + WordCount, 0);
  for (size_t I = 0; I < Str.size(); ++I)
    Words[Start + I / 4] |=
        static_cast<uint32_t>(static_cast<unsigned char>(Str[I]))
        << ((I % 4) * 8);
  return WordCount;
}

/// `VK_KHR_shader_non_semantic_info` (roadmap E19): the SPIR-V
/// specification defines every instruction in a `NonSemantic.*` extended
/// instruction set to have no effect on a module's semantics, and
/// explicitly permits a consumer that does not implement a given set to
/// ignore every `OpExtInst` referencing it. MLIR's own SPIR-V deserializer
/// has no generic "ignore" case for this, though --
/// `dispatchToExtensionSetAutogenDeserialization` fails outright for any
/// extended-instruction-set name it does not recognize by autogenerated
/// dispatch table, `NonSemantic.*` included -- so this ICD honors that
/// "ignorable" contract itself, at the one layer that can: strip the
/// `OpExtInstImport` that names such a set, and every `OpExtInst` that
/// references it, out of the binary word stream before MLIR ever sees it.
/// Any other extended-instruction-set import (e.g. `GLSL.std.450`, which
/// MLIR's dispatch table does recognize) is left untouched. Returns a copy
/// of \p Words with those instructions removed, or \p Words itself
/// (unmodified) if no `NonSemantic.*` import is present -- the common case,
/// so this is a no-op for every module that doesn't use the extension.
llvm::SmallVector<uint32_t>
stripNonSemanticExtInst(llvm::ArrayRef<uint32_t> Words) {
  if (Words.size() <= kSPIRVHeaderWords)
    return llvm::SmallVector<uint32_t>(Words);

  // First pass: find every `OpExtInstImport` result <id> naming a
  // `NonSemantic.*` set. A malformed instruction stream (bad word count,
  // truncated) is left for the real deserializer to reject -- this pass
  // only ever narrows what gets stripped, never invents new errors.
  llvm::DenseSet<uint32_t> NonSemanticSetIds;
  for (size_t I = kSPIRVHeaderWords; I < Words.size();) {
    uint32_t WordCount = Words[I] >> 16;
    uint32_t Opcode = Words[I] & 0xffff;
    if (WordCount == 0 || I + WordCount > Words.size())
      break;
    if (Opcode == kOpExtInstImport && WordCount >= 3) {
      unsigned NameIndex = static_cast<unsigned>(I + 2);
      std::string Name = decodeLiteralString(Words, NameIndex);
      if (llvm::StringRef(Name).starts_with("NonSemantic."))
        NonSemanticSetIds.insert(Words[I + 1]);
    }
    I += WordCount;
  }

  if (NonSemanticSetIds.empty())
    return llvm::SmallVector<uint32_t>(Words);

  // Second pass: copy every instruction except the `NonSemantic.*`
  // `OpExtInstImport`s found above and every `OpExtInst` referencing one of
  // them (its `Set` operand, the third operand -- word index `I + 3`).
  llvm::SmallVector<uint32_t> Result(Words.begin(),
                                     Words.begin() + kSPIRVHeaderWords);
  for (size_t I = kSPIRVHeaderWords; I < Words.size();) {
    uint32_t WordCount = Words[I] >> 16;
    uint32_t Opcode = Words[I] & 0xffff;
    if (WordCount == 0 || I + WordCount > Words.size()) {
      // Malformed tail: copy the rest verbatim and let the real
      // deserializer produce the error.
      Result.append(Words.begin() + I, Words.end());
      break;
    }
    bool IsNonSemanticImport = Opcode == kOpExtInstImport && WordCount >= 3 &&
                               NonSemanticSetIds.count(Words[I + 1]);
    bool IsNonSemanticExtInst = Opcode == kOpExtInst && WordCount >= 4 &&
                                NonSemanticSetIds.count(Words[I + 3]);
    if (!IsNonSemanticImport && !IsNonSemanticExtInst)
      Result.append(Words.begin() + I, Words.begin() + I + WordCount);
    I += WordCount;
  }
  return Result;
}

/// `mlir::spirv::Deserializer::processStructType` treats any `OpTypeStruct`
/// with an `OpName` debug string as an "identified" (named) struct type,
/// looked up and de-duplicated purely by that name string via
/// `spirv::StructType::getIdentified` -- with no scoping per distinct
/// SPIR-V <id> at all. A source-level HLSL struct nested at least three
/// `ConstantBuffer`/plain-struct levels deep needs two genuinely different
/// physical layouts for the same struct (one `ArrayStride`-16 Uniform-side
/// body, one `ArrayStride`-4 StorageBuffer-side body, say) -- DXC emits
/// both as separate `OpTypeStruct` <id>s, but names both with the same
/// plain source-level identifier (e.g. two distinct <id>s both named
/// "Z"). The deserializer then resolves both to the very same identified
/// `spirv::StructType` object and calls `trySetBody` on it twice with
/// disagreeing member layouts; `StructType::trySetBody` correctly refuses
/// to redefine an identified type's body a second time with different
/// content, but `processStructType` propagates that failure via a bare
/// `return failure();`, with no call to `emitError` first -- so this
/// entire class of module is rejected with zero diagnostic text at all
/// (confirmed via a direct `mlir-translate --deserialize-spirv` trace on a
/// minimized repro; `spirv-val` accepts the same module as valid SPIR-V,
/// so this is a deserializer-side gap, not a malformed-input one).
///
/// Rather than patch upstream MLIR's identified-struct-type table to be
/// <id>-scoped instead of name-scoped (a correct but much larger change,
/// deferred per roadmap H124d/H124m's own "large upstream-MLIR op/dialect
/// gap" precedent), this renames every `OpName` targeting an `OpTypeStruct`
/// <id> beyond the first one seen for a given name, appending that <id>'s
/// own numeric value as a suffix -- guaranteed unique, and semantically a
/// no-op, since `OpName`/`OpMemberName` are debug info only and never
/// participate in a module's real semantics. The renamed <id> then takes
/// `processStructType`'s `structIdentifier.empty()` literal/anonymous-
/// struct path instead of the identified-type path, sidestepping the
/// `trySetBody` collision entirely. Returns a copy of \p Words with those
/// `OpName` strings rewritten, or \p Words itself (unmodified) if no
/// struct name collision is present -- the common case.
llvm::SmallVector<uint32_t>
disambiguateDuplicateStructNames(llvm::ArrayRef<uint32_t> Words) {
  if (Words.size() <= kSPIRVHeaderWords)
    return llvm::SmallVector<uint32_t>(Words);

  // First pass: find every `OpTypeStruct` result <id>.
  llvm::DenseSet<uint32_t> StructIds;
  for (size_t I = kSPIRVHeaderWords; I < Words.size();) {
    uint32_t WordCount = Words[I] >> 16;
    uint32_t Opcode = Words[I] & 0xffff;
    if (WordCount == 0 || I + WordCount > Words.size())
      break;
    if (Opcode == kOpTypeStruct && WordCount >= 2)
      StructIds.insert(Words[I + 1]);
    I += WordCount;
  }

  if (StructIds.empty())
    return llvm::SmallVector<uint32_t>(Words);

  // Second pass: for every `OpName` targeting one of those <id>s, record
  // which struct <id>s share the same name string, in first-seen order.
  llvm::StringMap<llvm::SmallVector<uint32_t, 2>> StructIdsByName;
  for (size_t I = kSPIRVHeaderWords; I < Words.size();) {
    uint32_t WordCount = Words[I] >> 16;
    uint32_t Opcode = Words[I] & 0xffff;
    if (WordCount == 0 || I + WordCount > Words.size())
      break;
    if (Opcode == kOpName && WordCount >= 3 && StructIds.count(Words[I + 1])) {
      unsigned NameIndex = static_cast<unsigned>(I + 2);
      std::string Name = decodeLiteralString(Words, NameIndex);
      StructIdsByName[Name].push_back(Words[I + 1]);
    }
    I += WordCount;
  }

  llvm::DenseSet<uint32_t> IdsToRename;
  for (auto &Entry : StructIdsByName)
    for (uint32_t Id : llvm::drop_begin(Entry.second, 1))
      IdsToRename.insert(Id);

  if (IdsToRename.empty())
    return llvm::SmallVector<uint32_t>(Words);

  // Third pass: rebuild the module, rewriting every `OpName` (and its
  // matching `OpMemberName`, which shares its target-struct <id> as its
  // own operand 0) that targets a to-be-renamed <id> with a
  // guaranteed-unique "<original>.<id>" name.
  llvm::SmallVector<uint32_t> Result(Words.begin(),
                                     Words.begin() + kSPIRVHeaderWords);
  for (size_t I = kSPIRVHeaderWords; I < Words.size();) {
    uint32_t WordCount = Words[I] >> 16;
    uint32_t Opcode = Words[I] & 0xffff;
    if (WordCount == 0 || I + WordCount > Words.size()) {
      Result.append(Words.begin() + I, Words.end());
      break;
    }
    if (Opcode == kOpName && WordCount >= 3 &&
        IdsToRename.count(Words[I + 1])) {
      unsigned NameIndex = static_cast<unsigned>(I + 2);
      std::string Name = decodeLiteralString(Words, NameIndex);
      std::string Renamed = (Name + "." + llvm::Twine(Words[I + 1])).str();
      size_t OpStart = Result.size();
      Result.push_back(0); // Opcode/word-count patched in below.
      Result.push_back(Words[I + 1]);
      unsigned NameWords = appendLiteralString(Result, Renamed);
      Result[OpStart] =
          ((static_cast<uint32_t>(2 + NameWords)) << 16) | kOpName;
    } else {
      Result.append(Words.begin() + I, Words.begin() + I + WordCount);
    }
    I += WordCount;
  }
  return Result;
}

/// Opcodes this pass trusts to place a `Result Type` <id> operand
/// immediately after their `Result` <id> operand (i.e. the common
/// `(ResultType, Result, ...)` physical layout the SPIR-V specification's
/// "Instruction Physical Layout" section requires for every "value"
/// instruction) -- a small, deliberately conservative allowlist of the
/// producer opcodes real GLSL/HLSL-compiled shaders actually use to build
/// a sampling Coordinate/Dref operand or a plain-image query's own Image/
/// Level-of-Detail operand, rather than every opcode the specification
/// permits: an unrecognized producer simply means the rewrite calling
/// this (`lowerProjectiveImageSamples`/`lowerImageQueryOpcodes`) cannot
/// resolve that operand's exact type and leaves the instruction alone
/// (see each rewrite's own comment), so under-approximating this set only
/// costs coverage, never correctness.
bool isKnownResultTypeProducer(uint32_t Opcode) {
  switch (Opcode) {
  case 1:   // OpUndef
  case 12:  // OpExtInst
  case 43:  // OpConstant
  case 44:  // OpConstantComposite
  case 55:  // OpFunctionParameter
  case 57:  // OpFunctionCall
  case 61:  // OpLoad
  case 79:  // OpVectorShuffle
  case 80:  // OpCompositeConstruct
  case 81:  // OpCompositeExtract
  case 82:  // OpCompositeInsert
  case kOpImage: // OpImage: extracts a plain image out of a combined
                 // sampled image -- the shape a `sampler2D`-typed GLSL
                 // query builtin's own Image operand always takes.
  case 111: // OpConvertSToF
  case 112: // OpConvertUToF
  case 124: // OpBitcast
  case 127: // OpFNegate
  case 129: // OpFAdd
  case 131: // OpFSub
  case 133: // OpFMul
  case kOpFDiv:
  case 142: // OpVectorTimesScalar
  case 148: // OpDot
  case 169: // OpSelect
  case 245: // OpPhi
    return true;
  default:
    return false;
  }
}

/// Whether \p Words (the module's word stream, following the 5-word
/// header) contains at least one instruction whose opcode is in \p
/// Opcodes -- a cheap presence-only pre-check letting
/// `lowerProjectiveImageSamples`/`lowerImageQueryOpcodes` skip their own
/// more expensive `scanModuleTypes` call plus rewrite pass entirely for
/// the common case of a module using none of either rewrite's own
/// opcodes at all.
bool containsOpcode(llvm::ArrayRef<uint32_t> Words,
                    llvm::ArrayRef<uint32_t> Opcodes) {
  for (size_t I = kSPIRVHeaderWords; I < Words.size();) {
    uint32_t WordCount = Words[I] >> 16;
    uint32_t Opcode = Words[I] & 0xffff;
    if (WordCount == 0 || I + WordCount > Words.size())
      break;
    if (llvm::is_contained(Opcodes, Opcode))
      return true;
    I += WordCount;
  }
  return false;
}

/// The per-<id> type/vector-shape information both
/// `lowerProjectiveImageSamples` and `lowerImageQueryOpcodes` need to
/// resolve an operand's exact SPIR-V type from its defining instruction
/// (see `isKnownResultTypeProducer`'s own doc for why only a bounded
/// allowlist of producer opcodes is recognized), plus the module's first
/// `OpFunction` boundary either rewrite's own new type/synthetic-function
/// declarations must be inserted before.
struct TypeResolutionInfo {
  /// Every recognized value-producing instruction's Result <id> -> its
  /// Result-Type <id>.
  llvm::DenseMap<uint32_t, uint32_t> ValueType;
  /// Every `OpTypeVector`'s own Result <id> -> its (component-type <id>,
  /// component-count).
  llvm::DenseMap<uint32_t, std::pair<uint32_t, uint32_t>> VectorInfoByType;
  /// The inverse of `VectorInfoByType`: (component-type <id>,
  /// component-count) -> the `OpTypeVector` <id> already declaring that
  /// shape, if any.
  llvm::DenseMap<std::pair<uint32_t, uint32_t>, uint32_t> VectorTypeByComponent;
  /// Every `OpTypeFloat`'s own Result <id>.
  llvm::DenseSet<uint32_t> FloatTypeIds;
  /// The word index of the module's first `OpFunction` -- SPIR-V's own
  /// logical layout requires every type/global declaration to precede
  /// every function, so this is where a rewrite must insert any new one
  /// -- or `Words.size()` if the module has no function at all.
  size_t FuncStart;
};

/// Scans the whole module (not just one function -- an operand's defining
/// instruction and the instruction using it may be far apart, e.g. across
/// an inlined helper), building the type-resolution tables
/// `TypeResolutionInfo` documents.
TypeResolutionInfo scanModuleTypes(llvm::ArrayRef<uint32_t> Words) {
  TypeResolutionInfo Info;
  Info.FuncStart = Words.size();
  for (size_t I = kSPIRVHeaderWords; I < Words.size();) {
    uint32_t WordCount = Words[I] >> 16;
    uint32_t Opcode = Words[I] & 0xffff;
    if (WordCount == 0 || I + WordCount > Words.size())
      break;
    if (Opcode == kOpFunction && Info.FuncStart == Words.size())
      Info.FuncStart = I;
    if (Opcode == kOpTypeFloat && WordCount >= 2)
      Info.FloatTypeIds.insert(Words[I + 1]);
    if (Opcode == kOpTypeVector && WordCount >= 4) {
      Info.VectorInfoByType[Words[I + 1]] = {Words[I + 2], Words[I + 3]};
      Info.VectorTypeByComponent[{Words[I + 2], Words[I + 3]}] = Words[I + 1];
    }
    if (isKnownResultTypeProducer(Opcode) && WordCount >= 3)
      Info.ValueType[Words[I + 2]] = Words[I + 1];
    I += WordCount;
  }
  return Info;
}

/// Lowers SPIR-V's two "explicit-LOD projective" image-sampling opcodes --
/// `OpImageSampleProjExplicitLod` (92) and `OpImageSampleProjDrefExplicitLod`
/// (94) -- into the semantically equivalent non-projective opcodes MLIR's
/// own SPIR-V dialect already supports end-to-end
/// (`OpImageSampleExplicitLod`/`OpImageSampleDrefExplicitLod`, 88/90):
/// MLIR's autogenerated deserializer has no enum case for either "Proj"
/// opcode at all (`stringifyOpcode` returns empty for both -- see roadmap
/// L72(a)), so, mirroring `stripNonSemanticExtInst`'s own
/// rewrite-before-MLIR-ever-sees-it precedent, the module must be rewritten
/// here.
///
/// Per the SPIR-V specification, a "Proj" sampling opcode differs from its
/// non-Proj counterpart only in how its Coordinate (and, for the "Dref"
/// forms, its depth-reference) operand is interpreted: the Coordinate is
/// one component wider than the image's own dimensionality needs, and that
/// trailing "q" component is a projective divisor -- the real coordinate
/// (and Dref) used for the lookup is each other component divided by q.
/// This rewrite makes that division explicit: it inserts new
/// `OpCompositeExtract`/`OpFDiv`[/`OpCompositeConstruct`] instructions
/// immediately before the sample instruction to compute the divided,
/// narrowed Coordinate (and Dref), then relabels the instruction's own
/// opcode to the non-Proj equivalent. The Coordinate operand is narrowed
/// down to exactly the components the image's dimensionality needs --
/// not merely left at its original (wider) width with the extra component
/// divided in place and otherwise ignored, even though the specification
/// itself permits a Coordinate "vector larger than needed" for every
/// sampling opcode -- because `feme`'s own SPIR-V-to-LLVM legalization
/// (`ImageSampleExplicitLodPattern`/`ImageSampleDrefExplicitLodPattern`)
/// already assumes an exactly-sized Coordinate when selecting which
/// runtime entry point to call.
///
/// Deliberately conservative: an occurrence whose Coordinate (or Dref)
/// operand cannot be resolved back to a plain floating-point
/// `OpTypeVector` (or, for Dref, a plain floating-point scalar type) via
/// `isKnownResultTypeProducer`'s own bounded allowlist is left completely
/// untouched -- it simply remains an "unhandled opcode" import failure
/// exactly as before this rewrite existed, rather than risk silently
/// emitting an incorrect divide.
llvm::SmallVector<uint32_t>
lowerProjectiveImageSamples(llvm::ArrayRef<uint32_t> Words) {
  if (Words.size() <= kSPIRVHeaderWords ||
      !containsOpcode(Words, {kOpImageSampleProjExplicitLod,
                              kOpImageSampleProjDrefExplicitLod}))
    return llvm::SmallVector<uint32_t>(Words);

  TypeResolutionInfo Info = scanModuleTypes(Words);
  llvm::DenseMap<uint32_t, uint32_t> &ValueType = Info.ValueType;
  llvm::DenseMap<uint32_t, std::pair<uint32_t, uint32_t>> &VectorInfoByType =
      Info.VectorInfoByType;
  llvm::DenseMap<std::pair<uint32_t, uint32_t>, uint32_t>
      &VectorTypeByComponent = Info.VectorTypeByComponent;
  llvm::DenseSet<uint32_t> &FloatTypeIds = Info.FloatTypeIds;
  size_t FuncStart = Info.FuncStart;
  if (FuncStart == Words.size())
    return llvm::SmallVector<uint32_t>(Words);

  uint32_t Bound = Words[3];
  auto AllocId = [&Bound]() { return Bound++; };

  // Everything before the first `OpFunction` is copied verbatim, plus any
  // new `OpTypeVector` this pass needs to synthesize (appended as
  // encountered below -- still validly placed, since `Preamble` as a whole
  // precedes every function).
  llvm::SmallVector<uint32_t> Preamble(Words.begin(),
                                       Words.begin() + FuncStart);
  auto GetOrCreateVectorType = [&](uint32_t ComponentType,
                                   uint32_t Count) -> uint32_t {
    auto Key = std::make_pair(ComponentType, Count);
    auto It = VectorTypeByComponent.find(Key);
    if (It != VectorTypeByComponent.end())
      return It->second;
    uint32_t NewTypeId = AllocId();
    Preamble.push_back((4u << 16) | kOpTypeVector);
    Preamble.push_back(NewTypeId);
    Preamble.push_back(ComponentType);
    Preamble.push_back(Count);
    VectorTypeByComponent[Key] = NewTypeId;
    return NewTypeId;
  };

  // Second pass: copy every function-body instruction, rewriting each
  // "Proj" sample occurrence this pass can resolve as described above.
  llvm::SmallVector<uint32_t> Body;
  Body.reserve(Words.size() - FuncStart);
  auto Emit = [&Body](uint32_t Opcode,
                      std::initializer_list<uint32_t> Operands) {
    Body.push_back(((static_cast<uint32_t>(Operands.size()) + 1) << 16) |
                   Opcode);
    Body.append(Operands.begin(), Operands.end());
  };

  for (size_t I = FuncStart; I < Words.size();) {
    uint32_t WordCount = Words[I] >> 16;
    uint32_t Opcode = Words[I] & 0xffff;
    if (WordCount == 0 || I + WordCount > Words.size()) {
      // Malformed tail: copy the rest verbatim and let the real
      // deserializer produce the error.
      Body.append(Words.begin() + I, Words.end());
      break;
    }

    bool IsProjDref = Opcode == kOpImageSampleProjDrefExplicitLod;
    if (!IsProjDref && Opcode != kOpImageSampleProjExplicitLod) {
      Body.append(Words.begin() + I, Words.begin() + I + WordCount);
      I += WordCount;
      continue;
    }

    uint32_t ResultType = Words[I + 1];
    uint32_t Result = Words[I + 2];
    uint32_t SampledImage = Words[I + 3];
    uint32_t Coordinate = Words[I + 4];
    uint32_t Dref = IsProjDref ? Words[I + 5] : 0;
    size_t RestStart = IsProjDref ? I + 6 : I + 5;

    auto LeaveUnrewritten = [&]() {
      Body.append(Words.begin() + I, Words.begin() + I + WordCount);
      I += WordCount;
    };

    auto CoordTypeIt = ValueType.find(Coordinate);
    if (CoordTypeIt == ValueType.end()) {
      LeaveUnrewritten();
      continue;
    }
    auto VecInfoIt = VectorInfoByType.find(CoordTypeIt->second);
    if (VecInfoIt == VectorInfoByType.end()) {
      LeaveUnrewritten();
      continue;
    }
    uint32_t ComponentType = VecInfoIt->second.first;
    uint32_t TotalComponents = VecInfoIt->second.second;
    // A "Proj" Coordinate always has one extra (divisor) component beyond
    // what the image's own dimensionality needs, and that dimensionality
    // is 1D/2D/3D/Rect only (Cube is disallowed for every "Proj" opcode),
    // i.e. `TotalComponents` (needed-plus-divisor) must be in [2, 4].
    if (!FloatTypeIds.count(ComponentType) || TotalComponents < 2 ||
        TotalComponents > 4) {
      LeaveUnrewritten();
      continue;
    }
    uint32_t N = TotalComponents - 1;

    uint32_t DrefType = 0;
    if (IsProjDref) {
      auto DrefTypeIt = ValueType.find(Dref);
      if (DrefTypeIt == ValueType.end() ||
          !FloatTypeIds.count(DrefTypeIt->second)) {
        LeaveUnrewritten();
        continue;
      }
      DrefType = DrefTypeIt->second;
    }

    // `%q = OpCompositeExtract %ComponentType %Coordinate <N>` extracts the
    // trailing divisor component, then each of the `N` real coordinate
    // components is extracted and divided by it in turn.
    uint32_t QId = AllocId();
    Emit(kOpCompositeExtract, {ComponentType, QId, Coordinate, N});

    llvm::SmallVector<uint32_t, 3> DividedComponents;
    for (uint32_t Idx = 0; Idx < N; ++Idx) {
      uint32_t CId = AllocId();
      Emit(kOpCompositeExtract, {ComponentType, CId, Coordinate, Idx});
      uint32_t DId = AllocId();
      Emit(kOpFDiv, {ComponentType, DId, CId, QId});
      DividedComponents.push_back(DId);
    }

    uint32_t NewCoordinate;
    if (N == 1) {
      // A 1D image's Coordinate is a plain scalar, not a vector -- no new
      // vector type is needed, the sole divided component is the value.
      NewCoordinate = DividedComponents.front();
    } else {
      uint32_t VecTypeId = GetOrCreateVectorType(ComponentType, N);
      uint32_t NewCoordId = AllocId();
      Body.push_back(((static_cast<uint32_t>(N) + 3u) << 16) |
                     kOpCompositeConstruct);
      Body.push_back(VecTypeId);
      Body.push_back(NewCoordId);
      Body.append(DividedComponents.begin(), DividedComponents.end());
      NewCoordinate = NewCoordId;
    }

    uint32_t NewDref = Dref;
    if (IsProjDref) {
      uint32_t NewDrefId = AllocId();
      Emit(kOpFDiv, {DrefType, NewDrefId, Dref, QId});
      NewDref = NewDrefId;
    }

    // Re-emit the sample instruction itself: same word count, same every
    // operand except its own opcode (now the non-Proj equivalent) and its
    // now-narrowed Coordinate/Dref operands; `ImageOperands` and any
    // trailing operand words are copied through verbatim.
    Body.push_back((static_cast<uint32_t>(WordCount) << 16) |
                   (IsProjDref ? kOpImageSampleDrefExplicitLod
                               : kOpImageSampleExplicitLod));
    Body.push_back(ResultType);
    Body.push_back(Result);
    Body.push_back(SampledImage);
    Body.push_back(NewCoordinate);
    if (IsProjDref)
      Body.push_back(NewDref);
    Body.append(Words.begin() + RestStart, Words.begin() + I + WordCount);

    I += WordCount;
  }

  llvm::SmallVector<uint32_t> FinalWords;
  FinalWords.reserve(Preamble.size() + Body.size());
  FinalWords.append(Preamble.begin(), Preamble.end());
  FinalWords.append(Body.begin(), Body.end());
  FinalWords[3] = Bound;
  return FinalWords;
}

/// Lowers SPIR-V's `OpImageQuerySizeLod` (103), `OpImageQueryLevels`
/// (106), and `OpImageQuerySamples` (107) -- three opcodes MLIR's own
/// SPIR-V dialect has zero enum/Op-class coverage for at all (roadmap
/// L72(d), split out of L72(a) once that row's own rewrite closed out
/// `OpImageSampleProjExplicitLod`/`OpImageSampleProjDrefExplicitLod`, the
/// other two "unhandled opcode" opcodes; `OpImageQuerySamples` itself was
/// deferred out of L72(d) into its own follow-on row, L73, since it has a
/// separate prerequisite gap -- `SPIRVResourceLowering.cpp`'s own
/// `classifySampledImage2DHandle` rejecting every multisampled sampled
/// image handle outright -- blocking it even once this same import-time
/// encoding is in place) -- into an ordinary `OpFunctionCall` against a
/// synthesized, `Import`-linkage (i.e. declared-only, no body) external
/// function.
///
/// Unlike `lowerProjectiveImageSamples`'s own rewrite, none of these three
/// opcodes has a semantically equivalent *already-supported* SPIR-V
/// opcode to relabel into: each queries information (an image's own
/// mip-level count, its size at an explicit, possibly non-zero mip level,
/// or its own multisample sample count) no other already-supported
/// opcode's result can substitute for. Instead,
/// this rewrite gives MLIR something it already knows how to parse
/// end-to-end without any new opcode support at all: an `OpFunctionCall`
/// against a function declared with `Decoration LinkageAttributes ...
/// Import` (see mlir/lib/Target/SPIRV/Deserialization/Deserializer.cpp's
/// own `hasImportLinkage` handling, which erases such a function's body
/// requirement entirely) survives deserialization as an ordinary
/// `spirv.func`, and MLIR's own generic `FunctionCallPattern`/
/// `FuncConversionPattern` (mlir/lib/Conversion/SPIRVToLLVM/SPIRVToLLVM.cpp)
/// already lower both the call and the external declaration to a plain
/// `llvm.call` against an external `llvm.func`, named after this
/// function's own synthesized `OpName` (the deserializer's
/// `getFunctionSymbol` looks up a function's `OpName` first, falling back
/// to an auto-generated `spirv_fn_<id>` only if none was given) --
/// `SPIRVResourceLowering.cpp` then recognizes a call to one of this
/// rewrite's own magic-named functions (`isQuerySizeLodCall`/
/// `isQueryLevelsCall`/`isQuerySamplesCall`) the same way it already
/// recognizes an `llvm.spv.resource.*` intrinsic call, and lowers it to a
/// real runtime query.
///
/// This rewrite itself does not need to know an occurrence's eventual
/// image *shape* at all -- it only needs the Image (and, for
/// `OpImageQuerySizeLod`, Level-of-Detail) operand's own SPIR-V type,
/// resolved via `isKnownResultTypeProducer`'s bounded allowlist, exactly
/// as `lowerProjectiveImageSamples` resolves a Coordinate/Dref's -- so
/// every shape's occurrence is rewritten uniformly here.
/// `SPIRVResourceLowering.cpp`'s own `hasOnlySupportedImageUses` is what
/// actually scopes which shapes' synthesized calls survive:
/// `Plain2D`/`Array2D` for `OpImageQuerySizeLod`/`OpImageQueryLevels`
/// (roadmap L70's own `GetDimensions2D` shape-scoping precedent), and
/// `Plain2DMS`/`Array2DMS` for `OpImageQuerySamples` (roadmap L73, the
/// only shapes a multisampled sampled image can classify as) --
/// every other shape's occurrence is rewritten here the same as any
/// other, but still fails later, at that same shape check, exactly as it
/// did before this rewrite existed.
///
/// Deliberately conservative, mirroring `lowerProjectiveImageSamples`: an
/// occurrence whose Image (or Level-of-Detail) operand cannot be resolved
/// to a concrete type via `isKnownResultTypeProducer`'s own bounded
/// allowlist is left completely untouched -- it simply remains an
/// "unhandled opcode" import failure exactly as before this rewrite
/// existed.
llvm::SmallVector<uint32_t>
lowerImageQueryOpcodes(llvm::ArrayRef<uint32_t> Words) {
  if (Words.size() <= kSPIRVHeaderWords ||
      !containsOpcode(Words, {kOpImageQuerySizeLod, kOpImageQueryLevels,
                              kOpImageQuerySamples}))
    return llvm::SmallVector<uint32_t>(Words);

  TypeResolutionInfo Info = scanModuleTypes(Words);
  if (Info.FuncStart == Words.size())
    return llvm::SmallVector<uint32_t>(Words);

  uint32_t Bound = Words[3];
  auto AllocId = [&Bound]() { return Bound++; };

  // Everything before the first `OpFunction` is copied verbatim (the
  // 5-word header included), plus a one-time `OpCapability Linkage`
  // inserted right after the header (required by every synthesized
  // function's own `LinkageAttributes` decoration below -- see the SPIR-V
  // specification's own `Decoration LinkageAttributes` entry, which lists
  // `Linkage` as its sole required capability) and, per distinct (Opcode,
  // Image-type, Result-type[, Lod-type]) shape encountered below, one
  // synthesized external function declaration.
  llvm::SmallVector<uint32_t> Preamble(Words.begin(),
                                       Words.begin() + Info.FuncStart);
  Preamble.insert(Preamble.begin() + kSPIRVHeaderWords,
                  {(2u << 16) | kOpCapability, kCapabilityLinkage});

  // Memoizes one synthesized function per distinct (Opcode, Image-type
  // <id>, Result-type <id>, Lod-type <id> or 0) shape -- reusing the same
  // declaration for every occurrence with an identical shape, mirroring
  // `lowerProjectiveImageSamples`'s own `GetOrCreateVectorType`
  // memoization, rather than emitting a fresh (functionally harmless, but
  // redundant) declaration per occurrence.
  llvm::DenseMap<std::tuple<uint32_t, uint32_t, uint32_t, uint32_t>, uint32_t>
      SyntheticFunctions;
  uint32_t NextShapeIndex = 0;

  auto GetOrCreateSyntheticFunction = [&](uint32_t Opcode, uint32_t ImageType,
                                          uint32_t ResultType, uint32_t LodType,
                                          llvm::StringRef BaseName) {
    auto Key = std::make_tuple(Opcode, ImageType, ResultType, LodType);
    auto It = SyntheticFunctions.find(Key);
    if (It != SyntheticFunctions.end())
      return It->second;

    uint32_t FnTypeId = AllocId();
    uint32_t FnId = AllocId();
    uint32_t ImageParamId = AllocId();
    uint32_t LodParamId = LodType ? AllocId() : 0;

    // A distinct, human-readable name per synthesized shape both keeps
    // LLVM's own eventual function symbols apart (two distinct SPIR-V
    // types could otherwise convert to the same LLVM type and collide
    // under one shared name) and gives `SPIRVResourceLowering.cpp`'s own
    // recognition logic a stable prefix to match against.
    std::string Name = (BaseName + "." + llvm::Twine(NextShapeIndex++)).str();

    // `OpName %Fn "<Name>"`.
    size_t NameOpStart = Preamble.size();
    Preamble.push_back(0); // Opcode/word-count patched in below.
    Preamble.push_back(FnId);
    unsigned NameWords = appendLiteralString(Preamble, Name);
    Preamble[NameOpStart] =
        ((static_cast<uint32_t>(2 + NameWords)) << 16) | kOpName;

    // `OpDecorate %Fn LinkageAttributes "<Name>" Import`: the same string,
    // encoded a second time (`LinkageAttributes` carries its own copy of
    // the linkage name, distinct from any `OpName`) -- gives the
    // synthesized function `Import` linkage, so MLIR's own deserializer
    // treats it as an external declaration (no body) instead of requiring
    // one.
    size_t DecorateOpStart = Preamble.size();
    Preamble.push_back(0); // Opcode/word-count patched in below.
    Preamble.push_back(FnId);
    Preamble.push_back(kDecorationLinkageAttributes);
    unsigned DecorateNameWords = appendLiteralString(Preamble, Name);
    Preamble.push_back(kLinkageTypeImport);
    Preamble[DecorateOpStart] =
        ((static_cast<uint32_t>(3 + DecorateNameWords + 1)) << 16) |
        kOpDecorate;

    // `OpTypeFunction %FnTypeId %ResultType %ImageType [%LodType]`.
    llvm::SmallVector<uint32_t, 2> ParamTypes{ImageType};
    if (LodType)
      ParamTypes.push_back(LodType);
    Preamble.push_back(((static_cast<uint32_t>(3 + ParamTypes.size())) << 16) |
                       kOpTypeFunction);
    Preamble.push_back(FnTypeId);
    Preamble.push_back(ResultType);
    Preamble.append(ParamTypes.begin(), ParamTypes.end());

    // `OpFunction %ResultType %Fn None %FnTypeId`, immediately followed by
    // its parameter(s) and `OpFunctionEnd` -- no basic block/body at all,
    // valid only because of the `Import` linkage decorated above.
    Preamble.push_back((5u << 16) | kOpFunction);
    Preamble.push_back(ResultType);
    Preamble.push_back(FnId);
    Preamble.push_back(0); // FunctionControl::None.
    Preamble.push_back(FnTypeId);
    Preamble.push_back((3u << 16) | kOpFunctionParameter);
    Preamble.push_back(ImageType);
    Preamble.push_back(ImageParamId);
    if (LodType) {
      Preamble.push_back((3u << 16) | kOpFunctionParameter);
      Preamble.push_back(LodType);
      Preamble.push_back(LodParamId);
    }
    Preamble.push_back((1u << 16) | kOpFunctionEnd);

    SyntheticFunctions[Key] = FnId;
    return FnId;
  };

  // Second pass: copy every function-body instruction, rewriting each
  // occurrence of either opcode this pass can resolve into an
  // `OpFunctionCall` against the (possibly newly-synthesized) external
  // function for its exact shape.
  llvm::SmallVector<uint32_t> Body;
  Body.reserve(Words.size() - Info.FuncStart);
  for (size_t I = Info.FuncStart; I < Words.size();) {
    uint32_t WordCount = Words[I] >> 16;
    uint32_t Opcode = Words[I] & 0xffff;
    if (WordCount == 0 || I + WordCount > Words.size()) {
      Body.append(Words.begin() + I, Words.end());
      break;
    }

    bool IsSizeLod = Opcode == kOpImageQuerySizeLod;
    bool IsLevels = Opcode == kOpImageQueryLevels;
    bool IsSamples = Opcode == kOpImageQuerySamples;
    if (!IsSizeLod && !IsLevels && !IsSamples) {
      Body.append(Words.begin() + I, Words.begin() + I + WordCount);
      I += WordCount;
      continue;
    }

    uint32_t ResultType = Words[I + 1];
    uint32_t Result = Words[I + 2];
    uint32_t Image = Words[I + 3];
    uint32_t Lod = IsSizeLod ? Words[I + 4] : 0;

    auto LeaveUnrewritten = [&]() {
      Body.append(Words.begin() + I, Words.begin() + I + WordCount);
      I += WordCount;
    };

    auto ImageTypeIt = Info.ValueType.find(Image);
    if (ImageTypeIt == Info.ValueType.end()) {
      LeaveUnrewritten();
      continue;
    }
    uint32_t LodType = 0;
    if (IsSizeLod) {
      auto LodTypeIt = Info.ValueType.find(Lod);
      if (LodTypeIt == Info.ValueType.end()) {
        LeaveUnrewritten();
        continue;
      }
      LodType = LodTypeIt->second;
    }

    uint32_t FnId = GetOrCreateSyntheticFunction(
        Opcode, ImageTypeIt->second, ResultType, LodType,
        IsSizeLod  ? "feme.query.size_lod"
        : IsLevels ? "feme.query.levels"
                   : "feme.query.samples");

    unsigned NumArgs = IsSizeLod ? 2 : 1;
    Body.push_back(((4u + NumArgs) << 16) | kOpFunctionCall);
    Body.push_back(ResultType);
    Body.push_back(Result);
    Body.push_back(FnId);
    Body.push_back(Image);
    if (IsSizeLod)
      Body.push_back(Lod);

    I += WordCount;
  }

  llvm::SmallVector<uint32_t> FinalWords;
  FinalWords.reserve(Preamble.size() + Body.size());
  FinalWords.append(Preamble.begin(), Preamble.end());
  FinalWords.append(Body.begin(), Body.end());
  FinalWords[3] = Bound;
  return FinalWords;
}

} // namespace

llvm::Expected<Module> SPIRVImporter::import(llvm::MemoryBufferRef Buffer,
                                             const ImportOptions &Opts,
                                             Context &Ctx) const {
  // SPIR-V binaries are a stream of 32-bit words (see the SPIR-V
  // specification); reject inputs that cannot possibly be one rather than
  // reading past the end of the buffer.
  if (Buffer.getBufferSize() % sizeof(uint32_t) != 0)
    return llvm::createStringError(
        llvm::inconvertibleErrorCode(),
        "SPIR-V binary module must contain an integral number of 32-bit "
        "words");

  mlir::MLIRContext &MLIRCtx = Ctx.getMLIRContext();
  MLIRCtx.loadDialect<mlir::spirv::SPIRVDialect>();

  // `Buffer.getBufferStart()` has no alignment guarantee at all (it may
  // point into a `std::string`/string-literal-backed `StringRef`, neither
  // of which promises 4-byte alignment) -- reinterpret_cast'ing it
  // directly to `const uint32_t *` and reading through that pointer is
  // undefined behavior on a target where an unaligned load actually
  // traps (confirmed by a real UBSan `RejectsMalformedBinary` failure:
  // "load of misaligned address ... for type 'const unsigned int *'").
  // `llvm::support::endian::read32<native>` performs the same load via an
  // unaligned-safe memcpy under the hood, so copying every word through
  // it into a `SmallVector<uint32_t>` (whose own allocation is
  // word-aligned) is both portable and gives `stripNonSemanticExtInst`
  // the same word-array view it already expects.
  size_t WordCount = Buffer.getBufferSize() / sizeof(uint32_t);
  llvm::SmallVector<uint32_t> RawWords;
  RawWords.reserve(WordCount);
  const char *Data = Buffer.getBufferStart();
  for (size_t I = 0; I != WordCount; ++I)
    RawWords.push_back(llvm::support::endian::read32<llvm::endianness::native>(
        Data + I * sizeof(uint32_t)));
  llvm::SmallVector<uint32_t> Filtered = stripNonSemanticExtInst(RawWords);
  Filtered = lowerProjectiveImageSamples(Filtered);
  Filtered = lowerImageQueryOpcodes(Filtered);
  Filtered = disambiguateDuplicateStructNames(Filtered);
  llvm::ArrayRef<uint32_t> Binary = Filtered;

  mlir::spirv::DeserializationOptions DeserOpts;
  DeserOpts.enableControlFlowStructurization =
      Opts.SPIRVEnableControlFlowStructurization;

  bool MayRetry = DeserOpts.enableControlFlowStructurization &&
                  Opts.SPIRVFallBackToUnstructuredControlFlow;

  mlir::OwningOpRef<mlir::spirv::ModuleOp> SpirvModule;
  {
    // Only the *final* attempt's diagnostics should reach the caller: a
    // structurization failure that the retry below recovers from is not an
    // error the user needs to hear about.
    mlir::ScopedDiagnosticHandler Swallow(
        &MLIRCtx, [MayRetry](mlir::Diagnostic &) {
          return MayRetry ? mlir::success() : mlir::failure();
        });
    SpirvModule = mlir::spirv::deserialize(Binary, &MLIRCtx, DeserOpts);
  }

  if (!SpirvModule && MayRetry) {
    DeserOpts.enableControlFlowStructurization = false;
    SpirvModule = mlir::spirv::deserialize(Binary, &MLIRCtx, DeserOpts);
  }

  if (!SpirvModule)
    return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                   "failed to deserialize SPIR-V module");

  return Module::fromMLIR(std::move(SpirvModule));
}

llvm::StringRef SPIRVImporter::getFormatName() const { return "spirv"; }
