add_subdirectory(feme)
add_subdirectory(feme-opt)
add_subdirectory(feme-run)
add_subdirectory(feme-render)
add_subdirectory(feme-cfg-gen)
add_subdirectory(feme-translate)
add_subdirectory(feme-dxil-import-fuzzer)
add_subdirectory(feme-dxbc-import-fuzzer)
add_subdirectory(feme-spirv-import-fuzzer)
add_subdirectory(feme-cpu-restructure-fuzzer)
add_subdirectory(dxbc-as)
add_subdirectory(dxbc-as-fuzzer)
