#!/usr/bin/env python3
# embed_bitcode.py - Embeds an LLVM bitcode file as a C++ byte array.
#
# Part of the LLVM Project, under the Apache License v2.0 with LLVM
# Exceptions. See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# Usage: embed_bitcode.py <input.bc> <output.cpp> <symbol-basename>
#
# Generates a translation unit defining `extern const unsigned char
# <symbol-basename>Data[]` and `extern const unsigned
# <symbol-basename>Size`, for feme::cpu::getRuntimeCPUBitcode() (see
# feme/lib/Target/CPU/RuntimeCPU.cpp) to wrap in a `MemoryBufferRef` without
# any run-time file I/O -- the compiled shader module links against these
# bytes directly, per "Runtime Support Library" in
# feme/docs/FeMeCPUDesign.md.

import sys


def main():
    if len(sys.argv) != 4:
        sys.stderr.write(
            "usage: embed_bitcode.py <input.bc> <output.cpp> "
            "<symbol-basename>\n")
        return 1

    input_path, output_path, symbol = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(input_path, "rb") as f:
        data = f.read()

    with open(output_path, "w") as out:
        out.write("// Generated by embed_bitcode.py from %s. Do not edit.\n"
                  % input_path)
        out.write("extern const unsigned char %sData[] = {" % symbol)
        for i, byte in enumerate(data):
            if i % 16 == 0:
                out.write("\n  ")
            out.write("%d," % byte)
        out.write("\n};\n")
        out.write("extern const unsigned %sSize = %d;\n" % (symbol, len(data)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
