//===- RuntimeCPU.cpp - libFeMeRuntimeCPU bitcode accessor ---------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM
// Exceptions. See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#include "feme/Target/CPU/RuntimeCPU.h"

using namespace llvm;

// Generated by embed_bitcode.py (see runtime/CPU/CMakeLists.txt) from
// runtime/CPU/FeMeRuntimeCPU.c's compiled bitcode.
extern const unsigned char FeMeRuntimeCPUData[];
extern const unsigned FeMeRuntimeCPUSize;

MemoryBufferRef feme::cpu::getRuntimeCPUBitcode() {
  return MemoryBufferRef(
      StringRef(reinterpret_cast<const char *>(FeMeRuntimeCPUData),
                FeMeRuntimeCPUSize),
      "libFeMeRuntimeCPU");
}
