add_custom_target(FeMeUnitTests)
set_target_properties(FeMeUnitTests PROPERTIES FOLDER "FeMe/Tests")

function(add_feme_unittest test_dirname)
  add_unittest(FeMeUnitTests ${test_dirname} ${ARGN})
endfunction()

add_subdirectory(Conversion)
add_subdirectory(Core)
add_subdirectory(Driver)
add_subdirectory(DXBC)
add_subdirectory(Export)
add_subdirectory(Frontend)
add_subdirectory(Graphics)
add_subdirectory(Import)
add_subdirectory(Optimizer)
add_subdirectory(Runtime)
add_subdirectory(Target)
add_subdirectory(Translate)
add_subdirectory(Transforms)
