set(LLVM_LINK_COMPONENTS
  AsmParser
  Core
  Passes
  Scalar
  Support
  TestingSupport
  TransformUtils
  )

add_feme_unittest(FeMeTransformsCPUTests
  BuiltinCallsTest.cpp
  CFGGenTest.cpp
  EntryWrapperTest.cpp
  PrepareTest.cpp
  ReferenceEntryWrapperTest.cpp
  ReferenceLoweringTest.cpp
  ResourceCallsTest.cpp
  ResourceLoweringTest.cpp
  SIMDizeTest.cpp
  UnsupportedOpsTest.cpp
  VerifyStructuredTest.cpp
  WaveLoweringTest.cpp
  )
target_link_libraries(FeMeTransformsCPUTests
  PRIVATE
  FeMeTransformsCPU
  )
