set(LLVM_LINK_COMPONENTS
  AsmParser
  Core
  Support
  TestingSupport
  )

add_feme_unittest(FeMeTransformsCPUTests
  BuiltinCallsTest.cpp
  PrepareTest.cpp
  ResourceCallsTest.cpp
  ResourceLoweringTest.cpp
  SIMDizeTest.cpp
  UnsupportedOpsTest.cpp
  )
target_link_libraries(FeMeTransformsCPUTests
  PRIVATE
  FeMeTransformsCPU
  )
