set(LLVM_LINK_COMPONENTS
  AsmParser
  Core
  Passes
  Scalar
  Support
  TestingSupport
  TransformUtils
  )

add_feme_unittest(FeMeTransformsCPUTests
  BoundResourceNormalizationTest.cpp
  BuiltinCallsTest.cpp
  CFGGenTest.cpp
  EntryWrapperTest.cpp
  FragmentWrapperTest.cpp
  GroupSharedInfoTest.cpp
  HullWrapperTest.cpp
  LinearizeTest.cpp
  MaskIntrinsicsTest.cpp
  PrepareTest.cpp
  ReferenceEntryWrapperTest.cpp
  ReferenceLoweringTest.cpp
  ResourceCallsTest.cpp
  ResourceLoweringTest.cpp
  SIMDizeTest.cpp
  SPIRVResourceLoweringTest.cpp
  UnsupportedOpsTest.cpp
  VerifyStructuredTest.cpp
  VertexWrapperTest.cpp
  WaveCallsTest.cpp
  WaveLoweringTest.cpp
  )
target_link_libraries(FeMeTransformsCPUTests
  PRIVATE
  FeMeTransformsCPU
  FeMeTransformsDXIL
  )
